articles: 
- name: "npm"
  title: "Node Package Manager"
  markdown: true

- name: "sass"
  markdown: true
  chapters: 
    - "SASS_Maps"
    - "mixins"

- name: "bower"
  markdown: true

- name: "command-prompt"

- name: "gulp"
  markdown: true