articles: 
- name: npm
  icon: npm
  title: Node Package Manager
  markdown: true

- name: sass
  icon: sass
  markdown: true
  chapters: 
    - SASS_Maps
    - mixins

- name: bower
  icon: bower
  markdown: true

- name: gulp
  icon: gulp
  markdown: true